server:
  baseUri: "http://0.0.0.0:8081"

serviceAuth:
  clientId: platform_backend
  clientSecret: secret
  tokenEndpoint: http://hydra-public:4444/oauth2/token
  scope: SOURCEDATA.CREATE SOURCETYPE.UPDATE SOURCETYPE.DELETE AUTHORITY.UPDATE MEASUREMENT.DELETE PROJECT.READ AUDIT.CREATE USER.DELETE AUTHORITY.DELETE SUBJECT.DELETE MEASUREMENT.UPDATE SOURCEDATA.UPDATE SUBJECT.READ USER.UPDATE SOURCETYPE.CREATE AUTHORITY.READ USER.CREATE SOURCE.CREATE SOURCE.READ SUBJECT.CREATE ROLE.UPDATE ROLE.READ MEASUREMENT.READ PROJECT.UPDATE PROJECT.DELETE ROLE.DELETE SOURCE.DELETE SOURCETYPE.READ ROLE.CREATE SOURCEDATA.DELETE SUBJECT.UPDATE SOURCE.UPDATE PROJECT.CREATE AUDIT.READ MEASUREMENT.CREATE AUDIT.DELETE AUDIT.UPDATE AUTHORITY.CREATE USER.READ SOURCEDATA.READ

kratos:
  baseUrl: "http://kratos:4434"
  timeoutSeconds: 5
  maxRetries: 3
  endpoints:
    identities: "/admin/kratos/identities"
    identity: "/admin/kratos/identities/{id}"

managementPortal:
  baseUrl: "http://management-portal:8080/managementportal"
  timeoutSeconds: 5
  maxRetries: 3

logging:
  level: "INFO"
  file: "logs/user-service.log"
  pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
