auth:
  managementPortal:
    url: http://management-portal:8080
  resourceName: res_ManagementPortal
  issuer: http://hydra-public:4444
  publicKeyUrls: [
    "http://hydra-public:4444/.well-known/jwks.json"
  ]

contract:
  user: http://localhost:8081/user-service
  participant: http://localhost:8081/user-service
  project: http://localhost:8082/project-service
  config: http://localhost:8083/config-service
  dataSources: http://localhost:8084/data-sources-service


